# Generated by Django 2.2.16 on 2022-03-29 22:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='descriptions',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
