# Generated by Django 2.2.16 on 2022-03-31 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20220330_1643'),
    ]

    operations = [
        migrations.RenameField(
            model_name='title',
            old_name='categories',
            new_name='category',
        ),
        migrations.AlterField(
            model_name='title',
            name='descriptions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
