# Generated by Django 2.2.16 on 2022-04-03 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20220403_0905'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='title',
            name='descriptions',
        ),
    ]
