# Generated by Django 2.2.16 on 2022-04-03 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_remove_title_descriptions'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='descriptions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
