# Generated by Django 2.2.16 on 2022-04-03 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_title_descriptions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='descriptions',
            field=models.TextField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
