# Generated by Django 2.2.16 on 2022-03-31 04:12

import api.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_auto_20220330_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='score',
            field=models.IntegerField(validators=[api.validators.validate_score], verbose_name='Оценка'),
        ),
    ]
